version: '3.8'

services:
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - autobook-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - autobook-network

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/autobook_user_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - autobook-network

  conversation-service:
    build: ./conversation-service
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/autobook_conversation_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - autobook-network

  book-generation-service:
    build: ./book-generation-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/autobook_book_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092
      - OLLAMA_API_URL=http://host.docker.internal:11434
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    volumes:
      - book-data:/app/uploads
    networks:
      - autobook-network

  image-service:
    build: ./image-service
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    volumes:
      - image-data:/app/uploads
    networks:
      - autobook-network

  pdf-service:
    build: ./pdf-service
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    volumes:
      - pdf-data:/app/uploads
    networks:
      - autobook-network

  collection-service:
    build: ./collection-service
    ports:
      - "8086:8086"
    depends_on:
      - service-registry
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/autobook_collection_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - autobook-network

volumes:
  book-data:
  image-data:
  pdf-data:

networks:
  autobook-network:
    driver: bridge