version: '3.8'

services:
  # Service Registry (Eureka Server)
  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - autobook-network

  # API Gateway
  api-gateway:
    build: ./api-gateway-service
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - autobook-network

  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/autobook_user_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - autobook-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Conversation Service
  conversation-service:
    build: ./conversation-service
    container_name: conversation-service
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/autobook_conversation_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - autobook-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Book Generation Service
  book-generation-service:
    build: ./book-generation-service
    container_name: book-generation-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/autobook_book_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - OLLAMA_API_URL=http://host.docker.internal:11434
    networks:
      - autobook-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Image Service
  image-service:
    build: ./image-service
    container_name: image-service
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    volumes:
      - image-uploads:/app/uploads/images
    networks:
      - autobook-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # PDF Service
  pdf-service:
    build: ./pdf-service
    container_name: pdf-service
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    volumes:
      - pdf-uploads:/app/uploads/pdfs
      - preview-uploads:/app/uploads/previews
    networks:
      - autobook-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Collection Service
  collection-service:
    build: ./collection-service
    container_name: collection-service
    ports:
      - "8086:8086"
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/autobook_collection_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - autobook-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  autobook-network:
    driver: bridge

volumes:
  image-uploads:
  pdf-uploads:
  preview-uploads: