server:
  port: 8085
  servlet:
    context-path: /api/v1

spring:
  application:
    name: orchestration-service
  datasource:
    url: jdbc:postgresql://localhost:5432/autobook_orchestration
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

service:
  user-management:
    url: http://localhost:8081/api/v1
  storage:
    url: http://localhost:8082/api/v1
  payment:
    url: http://localhost:8083/api/v1
  text-generation:
    url: http://localhost:8000
  image-generation:
    url: http://localhost:8001
  pdf-assembly:
    url: http://localhost:8002

queue:
  text-generation: text-generation-queue
  image-generation: image-generation-queue
  pdf-assembly: pdf-assembly-queue
  notification: notification-queue

jwt:
  secret: your_jwt_secret_key_should_be_at_least_64_characters_long_and_stored_securely

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics